apiVersion: batch/v1
kind: Job
metadata:
  name: pytest-integration
spec:
  template:
    spec:
      containers:
      - name: pytest-runner
        image: pf9shalaka/pytest-runner:latest
        imagePullPolicy: Always
        # Optional: provide service connections via env:
        # env:
        # - name: SERVICE_HOST
        #   value: "my-service.default.svc.cluster.local"
      restartPolicy: Never
  backoffLimit: 0

